In [1]:
import pandas as pd
import numpy as np

In [2]:
imports = pd.read_csv('resources/imports.csv')
imports.set_index('Product',inplace=True)
# imports.index.names = ['Year']
imports = imports.T
imports.index.names = ['Year']
imports

Product,Dairy,Vegetables,Fruits,Other edible products,Meats,Fish and shellfish,Cereal and bakery foods
Year,,,,,,,
2022,407.2,"12,100.7","15,308.3","4,338.0","2,194.4","3,158.7","4,113.1"
2021,396.7,"13,349.0","14,768.3","3,079.1","2,077.5","3,111.5","3,654.9"
2020,392.8,"12,278.7","14,168.0","2,689.8","1,886.9","2,778.2","3,448.2"
2019,408.1,"11,763.4","13,882.4","2,437.6","1,795.5","2,704.9","3,122.6"
2018,379.9,"11,663.0","14,017.0","2,420.6","1,821.2","2,773.4","2,929.5"
2017,382.3,"11,070.2","13,606.2","2,250.1","1,847.8","2,669.9","2,704.1"
2016,395.6,"10,588.4","13,249.5","2,432.7","1,824.8","2,585.0","2,548.2"
2015,359.3,"9,733.1","12,861.1","2,396.0","1,942.8","2,525.0","2,287.6"
2014,302.5,"9,574.5","12,161.7","2,459.4","1,720.2","2,474.2","2,124.7"
2013,293.6,"8,989.3","11,833.3","2,342.7","1,400.5","2,399.7","2,024.7"
2012,292.0,"8,628.1","11,031.8","2,258.9","1,336.6","2,384.4","1,936.7"
2011,248.6,"8,440.9","10,466.4","2,222.3","1,270.1","2,349.4","1,881.7"
2010,249.7,"8,087.0","10,148.8","2,027.7","1,371.5","2,345.0","1,811.5"
2009,289.4,"7,312.6","9,495.2","1,839.3","1,445.4","2,248.8","1,666.9"
2008,309.8,"7,348.8","9,782.5","2,080.3","1,411.4","2,254.5","1,704.1"
2007,370.8,"7,204.5","9,933.5","1,996.9","1,628.2","2,288.1","1,759.7"
2006,375.6,"6,616.6","9,111.9","1,955.3","1,627.4","2,317.1","1,674.2"
2005,382.4,"6,368.6","8,757.5","1,832.5","1,797.1","2,199.5","1,640.6"
2004,346.4,"6,245.5","8,428.6","1,750.1","1,839.2","2,119.9","1,541.6"
2003,339.0,"5,967.2","8,288.9","1,532.9","1,659.3","2,082.4","1,489.4"
2002,332.8,"5,584.6","8,006.7","1,502.9","1,700.0","1,903.5","1,382.7"
2001,326.7,"5,139.6","7,556.8","1,403.4","1,634.0","1,759.0","1,226.8"
2000,298.9,"4,755.4","7,688.5","1,168.1","1,578.1","1,717.2","1,138.1"
1999,299.2,"4,790.1","7,870.2","1,099.2","1,439.6","1,689.8","1,071.1"